(function () {
  var STORAGE_KEY = 'bog_public_order_draft_v3';
  var LEGACY_KEY = 'bog_public_order_draft_v2';
  var STEPS = ['MENU', 'BURGERS', 'CUSTOM', 'EXTRAS', 'GUARNICIONES', 'DATOS', 'RESUMEN'];
  var MENU = {
    burgers: [
      { sku: 'OG', name: 'OG', price: 85, description: 'Carne "Especial" 250g aprox, tocino, queso americano, queso manchego, jitomate, lechuga, pepinillos, catsup, mostaza y mayonesa.' },
      { sku: 'BBQ', name: 'BBQ', price: 85, description: 'Carne "Especial" 250g aprox, tocino, queso americano, queso manchego, aros de cebolla, pepinillos y salsa BBQ.' }
    ],
    sides: [
      { sku: 'PAPAS_OG', name: 'Papas a la francesa OG', price: 20, description: 'papas clásicas, sal y crunch.' },
      { sku: 'PAPAS_ESPECIALES', name: 'Papas a la francesa Especiales', price: 25, description: 'papas con sazón especial de la casa.' },
      { sku: 'PAPAS_LEMON_PEPPER', name: 'Papas a la francesa Lemon&Pepper', price: 25, description: 'papas con toque cítrico y pimienta.' },
      { sku: 'AROS_CEBOLLA', name: 'Aros de Cebolla', price: 30, description: 'aros crujientes estilo burger joint.' }
    ],
    extras: [
      { sku: 'EXTRA_PEPINILLOS', name: 'Pepinillos', price: 5, description: 'toque ácido/crunch.' },{ sku: 'EXTRA_QUESO_AMERICANO', name: 'Queso americano', price: 5, description: 'extra cremoso clásico.' },{ sku: 'EXTRA_QUESO_MANCHEGO', name: 'Queso manchego', price: 5, description: 'extra fundido intenso.' },{ sku: 'EXTRA_TOCINO', name: 'Tocino', price: 5, description: 'crunch ahumado.' },{ sku: 'EXTRA_CATSUP', name: 'Catsup', price: 5, description: 'dulce clásica.' },{ sku: 'EXTRA_MOSTAZA', name: 'Mostaza', price: 5, description: 'punch ácido.' },{ sku: 'EXTRA_TOMATE', name: 'Tomate', price: 5, description: 'frescura extra.' }
    ]
  };
  var WITHOUT = { OG: ['Sin Tocino','Sin Queso americano','Sin Queso manchego','Sin Jitomate','Sin Lechuga','Sin Pepinillos','Sin Catsup','Sin Mostaza','Sin Mayonesa'], BBQ: ['Sin Tocino','Sin Queso americano','Sin Queso manchego','Sin Aros de cebolla','Sin Pepinillos','Sin Salsa bbq'] };
  var state = { step: 0, burgerUnits: [], sidesQty: {}, customer: { customerName: '', phone: '', location: '', paymentMethod: 'Pago mismo dia', note: '' }, ts: Date.now() };
  function bySku(list, sku) { return list.find(function (x) { return x.sku === sku; }); }
  function money(v) { return '$' + Number(v || 0).toFixed(2); }
  function burgerPrice(sku) { return bySku(MENU.burgers, sku).price; }
  function extraPrice(name) { return bySku(MENU.extras, 'EXTRA_' + name.toUpperCase().replace(/ /g, '_').replace('Ñ', 'N')) || { price: 5 }; }
  function syncUnits(counts) { var units = []; ['OG','BBQ'].forEach(function (sku) { for (var i = 1; i <= (counts[sku] || 0); i += 1) { var old = state.burgerUnits.find(function (u) { return u.id === sku + '-' + i; }); units.push(old || { id: sku + '-' + i, sku: sku, label: sku + ' #' + i, without: [], extras: [] }); } }); state.burgerUnits = units; }
  function countBurgers() { return state.burgerUnits.length; }
  function calcTotal() { var t = 0; state.burgerUnits.forEach(function (u) { t += burgerPrice(u.sku) + (u.extras || []).length * 5; }); MENU.sides.forEach(function (s) { t += (state.sidesQty[s.sku] || 0) * s.price; }); return t; }
  function renderStepper() { document.getElementById('stepper').innerHTML = STEPS.map(function (s, i) { return '<span class="step ' + (i === state.step ? 'active' : i < state.step ? 'done' : '') + '">' + s + '</span>'; }).join(''); }
  function cardList(items, qtyObj, prefix) { return items.map(function (x) { var q = qtyObj ? Number(qtyObj[x.sku] || 0) : 0; return '<article class="menu-item"><h3>' + x.name + '</h3><p>' + money(x.price) + '</p><small>' + x.description + '</small>' + (qtyObj ? '<div class="qty"><button data-op="minus" data-sku="' + x.sku + '">-</button><span>' + q + '</span><button data-op="plus" data-sku="' + x.sku + '">+</button></div>' : '') + '</article>'; }).join(''); }
  function renderStep() { var el = document.getElementById('stepContent'); var s = STEPS[state.step];
    if (s === 'MENU') el.innerHTML = '<h2>MENÚ</h2><h3>Burgers</h3><div class="menu-grid">' + cardList(MENU.burgers) + '</div><h3>Extras</h3><div class="menu-grid">' + cardList(MENU.extras) + '</div><h3>Guarniciones</h3><div class="menu-grid">' + cardList(MENU.sides) + '</div><button id="startBtn" class="primary">INICIAR PEDIDO</button>';
    if (s === 'BURGERS') { var counts = { OG: state.burgerUnits.filter(function (u) { return u.sku === 'OG'; }).length, BBQ: state.burgerUnits.filter(function (u) { return u.sku === 'BBQ'; }).length }; el.innerHTML = '<h2>BURGERS</h2><div class="menu-grid">' + cardList(MENU.burgers, counts) + '</div>'; }
    if (s === 'CUSTOM') el.innerHTML = '<h2>CUSTOM</h2>' + (state.burgerUnits.length ? state.burgerUnits.map(function (u, i) { return '<div class="custom-card"><h4>' + u.label + '</h4>' + WITHOUT[u.sku].map(function (opt) { return '<label><input type="checkbox" data-kind="without" data-i="' + i + '" value="' + opt + '" ' + (u.without.indexOf(opt) >= 0 ? 'checked' : '') + '>' + opt + '</label>'; }).join('') + '</div>'; }).join('') : '<p class="muted">No hay burgers.</p>');
    if (s === 'EXTRAS') el.innerHTML = '<h2>EXTRAS</h2>' + (state.burgerUnits.length ? state.burgerUnits.map(function (u, i) { return '<div class="custom-card"><h4>Extras para esta burger: ' + u.label + '</h4>' + MENU.extras.map(function (x) { return '<label><input type="checkbox" data-kind="extra" data-i="' + i + '" value="' + x.name + '" ' + (u.extras.indexOf(x.name) >= 0 ? 'checked' : '') + '>' + x.name + ' (+$5)</label>'; }).join('') + '</div>'; }).join('') : '<p class="muted">No hay burgers.</p>');
    if (s === 'GUARNICIONES') el.innerHTML = '<h2>GUARNICIONES</h2><div class="menu-grid">' + cardList(MENU.sides, state.sidesQty) + '</div>';
    if (s === 'DATOS') el.innerHTML = '<h2>DATOS</h2><label>Nombre<input id="name" value="' + state.customer.customerName + '"></label><label>Teléfono<input id="phone" value="' + state.customer.phone + '"></label><label>Ubicación<select id="location"><option value="">Selecciona</option><option ' + (state.customer.location === 'Torre GGA' ? 'selected' : '') + '>Torre GGA</option><option ' + (state.customer.location === 'Torre Valcob' ? 'selected' : '') + '>Torre Valcob</option></select></label><fieldset><legend>Forma de pago</legend><label><input type="radio" name="pay" value="Pago mismo dia" ' + (state.customer.paymentMethod === 'Pago mismo dia' ? 'checked' : '') + '>Pago mismo dia</label><label><input type="radio" name="pay" value="Pagar Antes" ' + (state.customer.paymentMethod === 'Pagar Antes' ? 'checked' : '') + '>Pagar Antes</label></fieldset><label>Nota<textarea id="note">' + state.customer.note + '</textarea></label>';
    if (s === 'RESUMEN') { var lines = state.burgerUnits.map(function (u) { var ex = (u.extras || []).map(function (n) { return n + ' +$5'; }).join(', ') || 'Sin extras'; return '<div class="ticket-line"><strong>' + u.label + ' — ' + money(burgerPrice(u.sku)) + '</strong><p>Quitar: ' + ((u.without || []).join(', ') || 'Sin cambios') + '</p><p>Extras: ' + ex + '</p><p>Subtotal burger: ' + money(burgerPrice(u.sku) + (u.extras || []).length * 5) + '</p></div>'; }).join(''); var sides = MENU.sides.map(function (s2) { var q = state.sidesQty[s2.sku] || 0; return q ? '<p>' + s2.name + ' x' + q + ' — ' + money(q * s2.price) + '</p>' : ''; }).join('') || '<p>Sin guarniciones</p>'; el.innerHTML = '<h2>RESUMEN</h2>' + (lines || '<p class="muted">Carrito vacío.</p>') + '<h3>Guarniciones</h3>' + sides + '<h3>TOTAL: ' + money(calcTotal()) + '</h3><p>Nombre: ' + state.customer.customerName + '</p><p>Teléfono: ' + state.customer.phone + '</p><p>Ubicación: ' + state.customer.location + '</p><p>Forma de pago: ' + state.customer.paymentMethod + '</p><p>Nota: ' + (state.customer.note || '(sin nota)') + '</p><div id="paymentInfo"></div><button id="submitBtn" class="primary">VALIDAR PEDIDO / COMPILAR ORDEN</button>'; renderPaymentInfo(); }
    toggleNav();
  }
  async function renderPaymentInfo() { var node = document.getElementById('paymentInfo'); if (!node) return; if (state.customer.paymentMethod === 'Pago mismo dia') { node.textContent = 'Pagas el día de entrega: efectivo o transferencia.'; return; } node.textContent = 'Cargando /api/bank-config...'; try { var r = await fetch('/api/bank-config'); var d = await r.json(); node.textContent = d.ok && d.data && d.data.enabled ? ('Banco: ' + (d.data.bankName || '') + ' | Titular: ' + (d.data.accountHolder || '') + ' | Cuenta: ' + (d.data.accountNumber || '')) : 'Datos bancarios pendientes de conectar'; } catch (_e) { node.textContent = 'Datos bancarios pendientes de conectar'; } }
  function buildPayload() { var items = {}; state.burgerUnits.forEach(function (u) { items[u.sku] = (items[u.sku] || 0) + 1; (u.extras || []).forEach(function (ex) { var sku = 'EXTRA_' + ex.toUpperCase().replace(/ /g, '_').replace('Ñ', 'N'); items[sku] = (items[sku] || 0) + 1; }); }); Object.keys(state.sidesQty).forEach(function (sku) { if (state.sidesQty[sku] > 0) items[sku] = (items[sku] || 0) + state.sidesQty[sku]; }); return { customerName: state.customer.customerName.trim(), phone: state.customer.phone.trim(), location: state.customer.location, paymentMethod: state.customer.paymentMethod, note: state.customer.note.trim(), items: Object.keys(items).map(function (sku) { return { sku: sku, qty: items[sku] }; }), personalizations: { burgers: state.burgerUnits.map(function (u, i) { return { sku: u.sku, burgerIndex: Number(u.id.split('-')[1] || (i + 1)), without: (u.without || []).slice(), extras: (u.extras || []).slice() }; }) }, timestamp: new Date().toISOString() }; }
  function validate(stepOnly) { if (!countBurgers() && state.step >= 1 && stepOnly !== 'submit') return 'Agrega al menos 1 burger.'; if ((state.step === 5 || stepOnly === 'submit') && (!state.customer.customerName.trim() || !state.customer.phone.trim() || !state.customer.location || !state.customer.paymentMethod)) return 'Completa datos requeridos.'; if (stepOnly === 'submit' && !buildPayload().items.length) return 'Carrito vacío.'; return ''; }
  function saveDraft() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
  function loadDraft() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || localStorage.getItem(LEGACY_KEY) || 'null'); } catch (_e) { return null; } }
  function restore(d) { if (!d) return; if (d.burgerUnits && d.customer) { state = d; return; } if (d.payload) { var counts = { OG: 0, BBQ: 0 }; (d.payload.items || []).forEach(function (it) { if (it.sku === 'OG' || it.sku === 'BBQ') counts[it.sku] = it.qty; }); syncUnits(counts); state.customer = { customerName: d.payload.customerName || '', phone: d.payload.phone || '', location: d.payload.location || '', paymentMethod: d.payload.paymentMethod || 'Pago mismo dia', note: d.payload.note || '' }; state.step = 0; } }
  function toggleNav() { document.getElementById('backBtn').disabled = state.step === 0; document.getElementById('nextBtn').style.display = state.step >= STEPS.length - 1 ? 'none' : 'inline-flex'; }
  function redraw() { renderStepper(); renderStep(); saveDraft(); }
  document.getElementById('stepContent').addEventListener('click', function (e) { var b = e.target.closest('button'); if (!b) return; if (b.id === 'startBtn') { state.step = 1; return redraw(); } if (b.id === 'submitBtn') return submit(); var sku = b.getAttribute('data-sku'); if (!sku) return; var op = b.getAttribute('data-op'); if (STEPS[state.step] === 'BURGERS') { var counts = { OG: state.burgerUnits.filter(function (u) { return u.sku === 'OG'; }).length, BBQ: state.burgerUnits.filter(function (u) { return u.sku === 'BBQ'; }).length }; counts[sku] = Math.max(0, (counts[sku] || 0) + (op === 'plus' ? 1 : -1)); syncUnits(counts); } else if (STEPS[state.step] === 'GUARNICIONES') state.sidesQty[sku] = Math.max(0, Number(state.sidesQty[sku] || 0) + (op === 'plus' ? 1 : -1)); redraw(); });
  document.getElementById('stepContent').addEventListener('change', function (e) { var t = e.target; var i = Number(t.getAttribute('data-i')); if (t.getAttribute('data-kind') === 'without') { var a = state.burgerUnits[i].without; var p = a.indexOf(t.value); if (t.checked && p < 0) a.push(t.value); if (!t.checked && p >= 0) a.splice(p, 1); } if (t.getAttribute('data-kind') === 'extra') { var earr = state.burgerUnits[i].extras; var ep = earr.indexOf(t.value); if (t.checked && ep < 0) earr.push(t.value); if (!t.checked && ep >= 0) earr.splice(ep, 1); } if (t.name === 'pay') state.customer.paymentMethod = t.value; if (t.id === 'location') state.customer.location = t.value; saveDraft(); });
  document.getElementById('stepContent').addEventListener('input', function (e) { var t = e.target; if (t.id === 'name') state.customer.customerName = t.value; if (t.id === 'phone') state.customer.phone = t.value; if (t.id === 'note') state.customer.note = t.value; saveDraft(); });
  document.getElementById('backBtn').addEventListener('click', function () { state.step = Math.max(0, state.step - 1); redraw(); });
  document.getElementById('nextBtn').addEventListener('click', function () { var err = validate(); if (err) return setStatus(err); state.step = Math.min(STEPS.length - 1, state.step + 1); redraw(); });
  document.getElementById('clearBtn').addEventListener('click', function () { localStorage.removeItem(STORAGE_KEY); localStorage.removeItem(LEGACY_KEY); state = { step: 0, burgerUnits: [], sidesQty: {}, customer: { customerName: '', phone: '', location: '', paymentMethod: 'Pago mismo dia', note: '' }, ts: Date.now() }; redraw(); setStatus('Nueva orden iniciada.'); });
  document.getElementById('loadLastBtn').addEventListener('click', function () { restore(loadDraft()); redraw(); setStatus('Draft cargado.'); });
  function setStatus(m, d) { document.getElementById('status').textContent = m + (d ? '\n\n' + JSON.stringify(d, null, 2) : ''); }
  async function submit() { var err = validate('submit'); if (err) return setStatus('Validación fallida: ' + err); var payload = buildPayload(); setStatus('Enviando /api/order...', payload); var r = await fetch('/api/order', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ payload: payload }) }); var d = await r.json(); setStatus((d.ok ? 'ORDER COMPILED' : 'Error en /api/order'), d); }
  restore(loadDraft()); redraw();
})();
