import { type ReactNode, useEffect, useMemo, useState } from 'react';
import * as Tabs from '@radix-ui/react-tabs';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { mockOrders, operatorStats, type MockOrder, type OrderStatus } from '@config/index';
import { Button, Card, StatusPill } from '@ui/index';

type TabKey = 'inicio' | 'pedidos' | 'cocina' | 'pagos' | 'historial';
const statusLabel: Record<OrderStatus, string> = { new: 'Nuevo', preparing: 'En preparación', ready: 'Listo', delivered: 'Entregado', cancelled: 'Cancelado' };
const statusTone: Record<OrderStatus, string> = { new: 'border-sky-400/40 text-sky-200', preparing: 'border-amber-400/40 text-amber-200', ready: 'border-emerald-400/40 text-emerald-200', delivered: 'border-zinc-500/40 text-zinc-200', cancelled: 'border-rose-500/40 text-rose-300' };

const StatusBadge = ({ status }: { status: OrderStatus }) => <StatusPill className={statusTone[status]}>{statusLabel[status]}</StatusPill>;
const CompactRow = ({ order, onOpen }: { order: MockOrder; onOpen: () => void }) => <Card className='p-2.5'><div className='flex items-start justify-between gap-2'><div><p className='text-sm font-bold'>{order.folio} · {order.customer}</p><p className='text-[11px] text-zinc-400'>{order.createdAt} · {order.channel} · {order.paymentMethod}/{order.paymentState}</p></div><StatusBadge status={order.status} /></div>{order.note ? <p className='mt-1.5 rounded bg-amber-500/10 px-2 py-1 text-[11px] text-amber-200'>Nota crítica: {order.note}</p> : null}<Button className='mt-2 border border-zinc-700 bg-zinc-900 py-1 text-[11px]' onClick={onOpen}>Abrir ticket</Button></Card>;
const PinLoginMock = ({ onLogin }: { onLogin: () => void }) => <main className='shell'><section className='login card'><h1>Internal Chekeo V2</h1><p className='muted'>Vista de prueba · acciones locales</p><label htmlFor='pin'>PIN</label><input id='pin' type='password' className='input' placeholder='••••' /><Button className='mt-3 bg-cyan-400 text-black' onClick={onLogin}>Entrar a consola</Button></section></main>;
const OperatorHeader = ({ active, onLogout }: { active: number; onLogout: () => void }) => <header className='card header-compact'><div><h1 className='text-sm font-bold md:text-base'>Burgers.exe Operator Console</h1><p className='text-[11px] text-zinc-400'>Activos {active} · {new Date().toLocaleTimeString()}</p></div><Button className='border border-zinc-700 bg-zinc-900 px-2 py-1 text-[11px]' onClick={onLogout}>Logout mock</Button></header>;
const DashboardHome = ({ orders }: { orders: MockOrder[] }) => <section className='grid gap-2.5 md:grid-cols-3'><Card className='p-2.5'><p className='muted'>Órdenes activas</p><p className='text-xl font-black'>{operatorStats.activeOrders}</p></Card><Card className='p-2.5'><p className='muted'>Pendientes</p><p className='text-xl font-black'>{operatorStats.pendingOrders}</p></Card><Card className='p-2.5'><p className='muted'>Carga cocina</p><p className='text-xl font-black'>{operatorStats.kitchenLoad}%</p></Card><Card className='md:col-span-2 p-2.5'><h3 className='mb-2 font-bold'>Urgentes ahora</h3>{orders.filter((o) => o.priority === 'urgent').map((o) => <div key={o.id} className='row'>{o.folio} · {o.customer} · {o.createdAt}</div>)}</Card><Card className='p-2.5'><h3 className='font-bold'>Estado del turno</h3><p className='muted'>Vista de prueba · acciones locales</p></Card></section>;
const OrdersBoard = ({ orders, setSelected }: { orders: MockOrder[]; setSelected: (o: MockOrder) => void }) => <section className='grid gap-2'>{orders.map((o) => <CompactRow key={o.id} order={o} onOpen={() => setSelected(o)} />)}</section>;
const KitchenQueue = ({ orders, move }: { orders: MockOrder[]; move: (id: string, s: OrderStatus) => void }) => <section className='grid gap-3 md:grid-cols-2'>{(['new', 'preparing', 'ready', 'delivered', 'cancelled'] as OrderStatus[]).map((s) => { const list = orders.filter((o) => o.status === s); return <Card key={s} className='p-3'><div className='mb-2 flex items-center justify-between'><h3 className='font-bold'>{statusLabel[s]}</h3><span className='chip'>{list.length}</span></div><div className='space-y-2'>{list.map((o) => { const canAdvance = o.status === 'new' || o.status === 'preparing' || o.status === 'ready'; const advanceLabel = o.status === 'ready' ? 'Entregar' : 'Avanzar'; const canMarkReady = o.status === 'new' || o.status === 'preparing'; const canCancel = o.status === 'new' || o.status === 'preparing'; const terminalLabel = o.status === 'delivered' ? 'Cerrado' : o.status === 'cancelled' ? 'Cancelado' : null; return <div key={o.id} className='row'><div><p className='text-xs font-semibold'>{o.folio} · {o.createdAt}</p><p className='text-[11px] text-zinc-400'>{o.customer} · {o.items[0]?.name}</p></div>{terminalLabel ? <span className='chip'>{terminalLabel}</span> : <div className='flex gap-1'>{canAdvance ? <button className='btn-sm' onClick={() => move(o.id, o.status === 'new' ? 'preparing' : o.status === 'preparing' ? 'ready' : 'delivered')}>{advanceLabel}</button> : null}{canMarkReady ? <button className='btn-sm' onClick={() => move(o.id, 'ready')}>Listo</button> : null}{canCancel ? <button className='btn-sm danger' onClick={() => move(o.id, 'cancelled')}>Cancelar</button> : null}</div>}</div>;})}</div></Card>;})}</section>;
const PaymentNotesPanel = ({ orders }: { orders: MockOrder[] }) => <section className='card'><h3 className='mb-2'>Pagos pendientes y notas</h3>{orders.filter((o) => o.paymentState === 'pending' || o.note).map((o) => <div key={o.id} className='row'><span>{o.folio} · {o.paymentMethod} · {o.createdAt}</span><span className='muted'>{o.note ?? 'Sin nota'}</span></div>)}</section>;
const HistoryMock = ({ orders }: { orders: MockOrder[] }) => <section className='card'><h3 className='mb-2'>Historial local</h3>{orders.filter((o) => o.status === 'delivered' || o.status === 'cancelled').map((o) => <div key={o.id} className='row'><span>{o.folio} · {o.createdAt}</span><StatusBadge status={o.status} /></div>)}</section>;
const getNextStatus = (status: OrderStatus): OrderStatus => (status === 'new' ? 'preparing' : status === 'preparing' ? 'ready' : status === 'ready' ? 'delivered' : status);

const OrderDetailModal = ({ selected, onClose, onMove }: { selected: MockOrder | null; onClose: () => void; onMove: (id: string, next: OrderStatus) => void }) => {
  useEffect(() => { const h = (e: KeyboardEvent) => e.key === 'Escape' && onClose(); window.addEventListener('keydown', h); return () => window.removeEventListener('keydown', h); }, [onClose]);
  if (!selected) return null;
  const nextStatus = getNextStatus(selected.status);
  const canAdvance = nextStatus !== selected.status;
  const canMarkReady = selected.status !== 'ready' && selected.status !== 'delivered' && selected.status !== 'cancelled';
  const canCancel = selected.status !== 'delivered' && selected.status !== 'cancelled';
  const runAction = (next: OrderStatus) => {
    onMove(selected.id, next);
    onClose();
  };
  return <div className='overlay' role='dialog' aria-modal='true' aria-labelledby='order-title' onClick={onClose}><section className='modal' onClick={(e) => e.stopPropagation()}><div className='flex items-start justify-between'><div><h2 id='order-title' className='text-lg font-black'>{selected.folio}</h2><p className='text-xs text-zinc-400'>{selected.customer} · {selected.createdAt} · {selected.channel}</p></div><StatusBadge status={selected.status} /></div><div className='mt-3 grid grid-cols-2 gap-2 text-sm'><p>Pago: {selected.paymentMethod}/{selected.paymentState}</p><p>Total: ${selected.total}</p></div><div className='mt-3 space-y-1 rounded-lg border border-dashed border-zinc-700 p-2'>{selected.items.map((i, idx) => <div key={idx} className='row'><span>{i.qty}x {i.name}</span><span>${i.price}</span></div>)}</div><div className='mt-3 rounded-lg border border-zinc-800 bg-zinc-900/60 p-2 text-xs text-zinc-300'>{selected.timeline.map((t) => <p key={t.id}>{t.time} · {t.label}</p>)}</div><div className='mt-3 flex flex-wrap gap-2'>{canAdvance ? <Button onClick={() => runAction(nextStatus)} className='flex-1 border border-zinc-700 bg-zinc-900 px-3 py-1.5 text-xs'>Avanzar</Button> : null}{canMarkReady ? <Button onClick={() => runAction('ready')} className='flex-1 border border-zinc-700 bg-zinc-900 px-3 py-1.5 text-xs'>Marcar listo</Button> : null}{canCancel ? <Button onClick={() => runAction('cancelled')} className='flex-1 border border-rose-700 bg-rose-950/50 px-3 py-1.5 text-xs text-rose-200'>Cancelar</Button> : null}</div><Button className='mt-2 w-full border border-zinc-700 bg-zinc-900 px-3 py-1.5 text-xs' onClick={onClose}>Cerrar</Button></section></div>;
};

const OperatorTabs = ({ tab, setTab, content }: { tab: TabKey; setTab: (v: TabKey) => void; content: ReactNode }) => <Tabs.Root value={tab} onValueChange={(v) => setTab(v as TabKey)}><Tabs.List className='tabs'>{[['inicio', 'Inicio'], ['pedidos', 'Pedidos'], ['cocina', 'Cocina'], ['pagos', 'Pagos'], ['historial', 'Historial']].map(([k, l]) => <Tabs.Trigger key={k} value={k} className='tab'>{l}</Tabs.Trigger>)}</Tabs.List>{content}</Tabs.Root>;

export function InternalChekeoApp() {
  const [logged, setLogged] = useState(false); const [tab, setTab] = useState<TabKey>('inicio'); const [orders, setOrders] = useState(mockOrders); const [selected, setSelected] = useState<MockOrder | null>(null); const reduce = useReducedMotion();
  const active = orders.filter((o) => o.status !== 'delivered' && o.status !== 'cancelled');
  const move = (id: string, s: OrderStatus) => setOrders((p) => p.map((o) => (o.id === id ? { ...o, status: s } : o)));
  const content = useMemo(() => ({ inicio: <DashboardHome orders={orders} />, pedidos: <OrdersBoard orders={orders} setSelected={setSelected} />, cocina: <KitchenQueue orders={orders} move={move} />, pagos: <PaymentNotesPanel orders={orders} />, historial: <HistoryMock orders={orders} /> })[tab], [orders, tab]);
  if (!logged) return <PinLoginMock onLogin={() => setLogged(true)} />;
  return <main className='shell'><OperatorHeader active={active.length} onLogout={() => setLogged(false)} /><OperatorTabs tab={tab} setTab={setTab} content={<AnimatePresence mode='wait'><motion.div key={tab} initial={reduce ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={reduce ? {} : { opacity: 0, y: -8 }} transition={{ duration: 0.18 }} className='mt-2'>{content}</motion.div></AnimatePresence>} /><OrderDetailModal selected={selected} onClose={() => setSelected(null)} onMove={move} /></main>;
}
