import { type ReactNode, useEffect, useMemo, useState } from 'react';
import * as Tabs from '@radix-ui/react-tabs';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { mockOrders, operatorStats, type MockOrder, type OrderStatus } from '@config/index';
import { Button, Card, SectionHeader, StatusPill } from '@ui/index';

type TabKey = 'inicio' | 'pedidos' | 'cocina' | 'pagos' | 'historial';
const statusLabel: Record<OrderStatus, string> = { new: 'Nuevo', preparing: 'En preparación', ready: 'Listo', delivered: 'Entregado', cancelled: 'Cancelado' };
const statusTone: Record<OrderStatus, string> = { new: 'border-sky-400/40 text-sky-200', preparing: 'border-amber-400/40 text-amber-200', ready: 'border-emerald-400/40 text-emerald-200', delivered: 'border-zinc-500/40 text-zinc-200', cancelled: 'border-rose-500/40 text-rose-300' };
type OperatorShellProps = { active: number; onLogout: () => void; children: ReactNode };

const KpiCard = ({ label, value }: { label: string; value: number }) => <Card><p className='text-sm text-zinc-400'>{label}</p><p className='text-3xl font-black'>{value}</p></Card>;
const StatusBadge = ({ status }: { status: OrderStatus }) => <StatusPill className={statusTone[status]}>{statusLabel[status]}</StatusPill>;
const OrderCard = ({ order, onOpen }: { order: MockOrder; onOpen: () => void }) => <Card><div className='flex items-center justify-between'><strong>{order.folio} · {order.customer}</strong><StatusBadge status={order.status} /></div><p className='mt-1 text-sm text-zinc-400'>{order.items.length} items · ${order.total} · {order.paymentMethod}/{order.paymentState}</p><Button className='mt-3 border border-zinc-700 bg-zinc-900' onClick={onOpen}>Ver detalle</Button></Card>;
const PinLoginMock = ({ onLogin }: { onLogin: () => void }) => <main className='shell'><section className='login card'><h1>Internal Chekeo V2</h1><p className='muted'>V2 mock / no conecta sesión real</p><label htmlFor='pin'>PIN</label><input id='pin' type='password' className='input' placeholder='••••' /><Button className='mt-3 bg-cyan-400 text-black' onClick={onLogin}>Entrar a consola</Button></section></main>;
const OperatorHeader = ({ active, onLogout }: { active: number; onLogout: () => void }) => <header className='card flex flex-wrap items-center justify-between gap-2'><div><h1 className='text-xl font-bold'>Burgers.exe Operator Console</h1><p className='muted'>Activos {active} · {new Date().toLocaleTimeString()}</p></div><Button className='border border-zinc-700 bg-zinc-900' onClick={onLogout}>Logout mock</Button></header>;
const DashboardHome = ({ orders }: { orders: MockOrder[] }) => <section className='grid gap-3 md:grid-cols-3'><KpiCard label='Órdenes activas' value={operatorStats.activeOrders} /><KpiCard label='Pendientes' value={operatorStats.pendingOrders} /><KpiCard label='Carga cocina %' value={operatorStats.kitchenLoad} /><Card className='md:col-span-2'><h3 className='mb-2 font-bold'>Pedidos urgentes</h3>{orders.filter((o) => o.priority === 'urgent').map((o) => <div key={o.id} className='row'>{o.folio} · {o.customer}</div>)}</Card><Card><h3 className='font-bold'>Actividad</h3><p className='muted'>Operación estable · mock success</p></Card></section>;
const OrdersBoard = ({ orders, setSelected }: { orders: MockOrder[]; setSelected: (o: MockOrder) => void }) => <section className='grid gap-3'>{orders.map((o) => <OrderCard key={o.id} order={o} onOpen={() => setSelected(o)} />)}</section>;
const KitchenQueue = ({ orders, move }: { orders: MockOrder[]; move: (id: string, s: OrderStatus) => void }) => <section className='grid gap-3 md:grid-cols-2'>{(['new', 'preparing', 'ready', 'delivered'] as OrderStatus[]).map((s) => <Card key={s}><SectionHeader title={statusLabel[s]} /><div className='mt-2 space-y-2'>{orders.filter((o) => o.status === s).map((o) => <div key={o.id} className='row'><span>{o.folio}</span><div className='flex gap-1'><button className='btn-sm' onClick={() => move(o.id, s === 'new' ? 'preparing' : s === 'preparing' ? 'ready' : 'delivered')}>Mover</button><button className='btn-sm' onClick={() => move(o.id, 'ready')}>Listo</button><button className='btn-sm danger' onClick={() => move(o.id, 'cancelled')}>Cancelar</button></div></div>)}</div></Card>)}</section>;
const PaymentNotesPanel = ({ orders }: { orders: MockOrder[] }) => <section className='card'><h3>Pagos pendientes y notas</h3>{orders.filter((o) => o.paymentState === 'pending' || o.note).map((o) => <div key={o.id} className='row'><span>{o.folio} · {o.paymentMethod}</span><span className='muted'>{o.note ?? 'Sin nota'}</span></div>)}</section>;
const HistoryMock = ({ orders }: { orders: MockOrder[] }) => <section className='card'><h3>Historial mock</h3>{orders.filter((o) => o.status === 'delivered' || o.status === 'cancelled').map((o) => <div key={o.id} className='row'><span>{o.folio}</span><StatusBadge status={o.status} /></div>)}</section>;
const OrderDetailModal = ({ selected, onClose }: { selected: MockOrder | null; onClose: () => void }) => {
  useEffect(() => { const h = (e: KeyboardEvent) => e.key === 'Escape' && onClose(); window.addEventListener('keydown', h); return () => window.removeEventListener('keydown', h); }, [onClose]);
  if (!selected) return null;
  return <div className='overlay' role='dialog' aria-modal='true' aria-labelledby='order-title' onClick={onClose}><section className='modal' onClick={(e) => e.stopPropagation()}><h2 id='order-title'>{selected.folio} detalle</h2><p className='muted'>{selected.customer}</p><div className='mt-2 space-y-1'>{selected.items.map((i, idx) => <div key={idx} className='row'><span>{i.qty}x {i.name}</span><span>${i.price}</span></div>)}</div><p className='muted mt-2'>Timeline: {selected.timeline.map((t) => `${t.time} ${t.label}`).join(' · ')}</p><Button className='mt-3 border border-zinc-700 bg-zinc-900' onClick={onClose}>Cerrar</Button></section></div>;
};
const OperatorTabs = ({ tab, setTab, content }: { tab: TabKey; setTab: (v: TabKey) => void; content: ReactNode }) => <Tabs.Root value={tab} onValueChange={(v) => setTab(v as TabKey)}><Tabs.List className='tabs'>{[['inicio', 'Inicio'], ['pedidos', 'Pedidos'], ['cocina', 'Cocina'], ['pagos', 'Pagos/Notas'], ['historial', 'Historial']].map(([k, l]) => <Tabs.Trigger key={k} value={k} className='tab'>{l}</Tabs.Trigger>)}</Tabs.List>{content}</Tabs.Root>;
const OperatorShell = ({ active, onLogout, children }: OperatorShellProps) => <main className='shell'><OperatorHeader active={active} onLogout={onLogout} />{children}</main>;

export function InternalChekeoApp() {
  const [logged, setLogged] = useState(false); const [tab, setTab] = useState<TabKey>('inicio'); const [orders, setOrders] = useState(mockOrders); const [selected, setSelected] = useState<MockOrder | null>(null); const reduce = useReducedMotion();
  const active = orders.filter((o) => o.status !== 'delivered' && o.status !== 'cancelled');
  const move = (id: string, s: OrderStatus) => setOrders((p) => p.map((o) => (o.id === id ? { ...o, status: s } : o)));
  const content = useMemo(() => ({ inicio: <DashboardHome orders={orders} />, pedidos: <OrdersBoard orders={orders} setSelected={setSelected} />, cocina: <KitchenQueue orders={orders} move={move} />, pagos: <PaymentNotesPanel orders={orders} />, historial: <HistoryMock orders={orders} /> })[tab], [orders, tab]);
  if (!logged) return <PinLoginMock onLogin={() => setLogged(true)} />;
  return <OperatorShell active={active.length} onLogout={() => setLogged(false)}><OperatorTabs tab={tab} setTab={setTab} content={<AnimatePresence mode='wait'><motion.div key={tab} initial={reduce ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={reduce ? {} : { opacity: 0, y: -8 }} transition={{ duration: 0.18 }} className='mt-3'>{content}</motion.div></AnimatePresence>} /><OrderDetailModal selected={selected} onClose={() => setSelected(null)} /></OperatorShell>;
}
